// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CustomerMatterManagementAPI;

public partial class Matter
{
    public int MatterId { get; set; }

    public int CustomerId { get; set; }

    public string Title { get; set; } = null!;

    public string? Description { get; set; }

}