// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace cmManagement;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string Name { get; set; } = null!;

    public string PhoneNum { get; set; } = null!;

    public virtual Customer CustomerNavigation { get; set; } = null!;

    public virtual Customer? InverseCustomerNavigation { get; set; }

    public virtual ICollection<Matter> Matters { get; set; } = new List<Matter>();
}