// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace cmManagement;

public partial class User
{
    public int UserId { get; set; }

    public string EmailAddr { get; set; } = null!;

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public byte[] Password { get; set; } = null!;

    public string FirmName { get; set; } = null!;
}